fix: get rid snail_case
ivyoverflow/pub-sub pull request #21
Opened 2021-02-01 11:26 UTC by ivyoverflow

#10 is closed.

2021-02-02 07:37 UTC, kiryalovik requested changes

2021-02-02 07:37 UTC, kiryalovik commented on book/internal/handler/book_test.go
> +	mockrepository "github.com/ivyoverflow/pub-sub/book/internal/repository/mock"
You can use some abbreviation like `repomock`, `svcmock` etc.

2021-02-02 07:37 UTC, kiryalovik commented on book/internal/handler/book_test.go
> +		mockBehaviorIDGenerator func(*mockservice.MockIDGeneratorI)
When you name some structure inside the package you don't need to duplicate package naming: 
`svcmock.IDGenerator`. And why there's `I` at the end of the name. Is it an interface in the mock package?

2021-02-02 17:03 UTC, ivyoverflow commented on book/internal/handler/book_test.go
> +		mockBehaviorIDGenerator func(*mockservice.MockIDGeneratorI)
Well, the mocks are generated automatically and I cannot change the mock.go file.

2021-02-02 17:04 UTC, ivyoverflow commented on book/internal/handler/book_test.go
> +	mockrepository "github.com/ivyoverflow/pub-sub/book/internal/repository/mock"
Yeah, thanks, changes [here](https://github.com/ivyoverflow/pub-sub/pull/21/commits/1641b14edd69bdcb61b717778ada3f80b55bf784).

2021-02-02 19:11 UTC, kiryalovik commented on book/internal/handler/book_test.go
> +		mockBehaviorIDGenerator func(*mockservice.MockIDGeneratorI)
https://golang.org/doc/effective_go.html#interface-names

2021-02-02 19:13 UTC, kiryalovik commented on book/internal/handler/book_test.go
> +		mockBehaviorIDGenerator func(*mockservice.MockIDGeneratorI)
-mock_names: A list of custom names for generated mocks. This is specified as a comma-separated list of elements of the form Repository=MockSensorRepository,Endpoint=MockSensorEndpoint, where Repository is the interface name and MockSensorRepository is the desired mock name (mock factory method and mock recorder will be named after the mock). If one of the interfaces has no custom name specified, then default naming convention will be used

https://github.com/golang/mock

2021-02-03 13:49 UTC, ivyoverflow commented on book/internal/handler/book_test.go
> +		mockBehaviorIDGenerator func(*mockservice.MockIDGeneratorI)
I've uploaded the solution.

2021-02-15 10:01 UTC, merged